In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
data=pd.read_csv("https://raw.githubusercontent.com/BigDataGal/Python-for-Data-Science/master/titanic-train.csv")

In [4]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
data.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [7]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
cat_columns=[col  for col in data.columns if data[col].dtypes=="O"]

In [10]:
cat_columns

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [11]:
### Let's Drop Name ,Ticket and Cabin column

In [12]:
data.drop(["Name","Ticket","Cabin"],axis=1,inplace=True)

In [13]:
data.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [14]:
## Also Drop Passenger ID columns

In [15]:
data.drop(["PassengerId"],axis=1,inplace=True)

In [17]:
data["Age"].fillna(data["Age"].median(),inplace=True)

In [18]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [19]:
data["Embarked"].fillna(data["Embarked"].mode()[0],inplace=True)

In [20]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [21]:
data.Embarked.unique()

array(['S', 'C', 'Q'], dtype=object)

In [22]:
data["Sex"].replace({"male":1,"female":0},inplace=True)

In [23]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S

In [24]:
data=pd.get_dummies(data,columns=["Embarked"],drop_first=True)

In [25]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         0       3    1  22.0      1      0   7.2500           0           1
1         1       1    0  38.0      1      0  71.2833           0           0
2         1       3    0  26.0      0      0   7.9250           0           1
3         1       1    0  35.0      1      0  53.1000           0           1
4         0       3    1  35.0      0      0   8.0500           0           1

In [26]:
X=data.iloc[:,1:]
y=data.iloc[:,0]

In [27]:
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0       3    1  22.0      1      0   7.2500           0           1
1       1    0  38.0      1      0  71.2833           0           0
2       3    0  26.0      0      0   7.9250           0           1
3       1    0  35.0      1      0  53.1000           0           1
4       3    1  35.0      0      0   8.0500           0           1

In [28]:
train_X,test_X,train_y,test_y=train_test_split(X,y,test_size=0.3,random_state=100)

In [29]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [30]:
sc=StandardScaler()

In [31]:
train_X=sc.fit_transform(train_X)
test_X=sc.transform(test_X)

In [33]:
lr_classifier=LogisticRegression()
lr_classifier.fit(train_X,train_y)

LogisticRegression()

In [35]:
log_pred=lr_classifier.predict(test_X)

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [37]:
print(accuracy_score(test_y,log_pred))
print(classification_report(test_y,log_pred))
confusion_matrix(test_y,log_pred)

0.7910447761194029
              precision    recall  f1-score   support

           0       0.79      0.87      0.83       159
           1       0.78      0.67      0.72       109

    accuracy                           0.79       268
   macro avg       0.79      0.77      0.78       268
weighted avg       0.79      0.79      0.79       268



array([[139,  20],
       [ 36,  73]], dtype=int64)

In [39]:
dt=DecisionTreeClassifier()
dt.fit(train_X,train_y)

DecisionTreeClassifier()

In [42]:
accuracy_score(train_y,dt.predict(train_X))

0.985553772070626

In [40]:
dt_pred=dt.predict(test_X)

In [41]:
print(accuracy_score(test_y,dt_pred))
print(classification_report(test_y,dt_pred))
confusion_matrix(test_y,dt_pred)

0.7761194029850746
              precision    recall  f1-score   support

           0       0.81      0.81      0.81       159
           1       0.72      0.72      0.72       109

    accuracy                           0.78       268
   macro avg       0.77      0.77      0.77       268
weighted avg       0.78      0.78      0.78       268



array([[129,  30],
       [ 30,  79]], dtype=int64)

In [43]:
## Let's Perform Grid Searh

In [44]:
# we are tuning three hyperparameters right now, we are passing the different values for both parameters
grid_param = {
    'criterion': ['gini', 'entropy'],
    'max_depth' : range(2,20,1),
    'min_samples_leaf' : range(1,10,1),
    'min_samples_split': range(2,10,1),    
}

In [45]:
from sklearn.model_selection import GridSearchCV

In [47]:
grid_search=GridSearchCV(DecisionTreeClassifier(),param_grid=grid_param,cv=10,n_jobs=-1,scoring="accuracy",verbose=2)

In [48]:
grid_search.fit(train_X,train_y)

Fitting 10 folds for each of 2592 candidates, totalling 25920 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  74 tasks      | elapsed:   11.9s
[Parallel(n_jobs=-1)]: Done 2002 tasks      | elapsed:   21.0s
[Parallel(n_jobs=-1)]: Done 5874 tasks      | elapsed:   37.1s
[Parallel(n_jobs=-1)]: Done 14930 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 25884 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-1)]: Done 25920 out of 25920 | elapsed:  2.3min finished


GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(2, 20),
                         'min_samples_leaf': range(1, 10),
                         'min_samples_split': range(2, 10)},
             scoring='accuracy', verbose=2)

In [49]:
grid_search.best_score_

0.8332053251408091

In [50]:
grid_search.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_leaf=2,
                       min_samples_split=8)

In [51]:
clf=DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_leaf=2,
                       min_samples_split=8)

In [52]:
clf.fit(train_X,train_y)

DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_leaf=2,
                       min_samples_split=8)

In [54]:
pred=clf.predict(test_X)

In [55]:
print(accuracy_score(test_y,pred))
print(classification_report(test_y,pred))
confusion_matrix(test_y,pred)

0.8059701492537313
              precision    recall  f1-score   support

           0       0.80      0.89      0.85       159
           1       0.81      0.68      0.74       109

    accuracy                           0.81       268
   macro avg       0.81      0.79      0.79       268
weighted avg       0.81      0.81      0.80       268



array([[142,  17],
       [ 35,  74]], dtype=int64)